language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - kimji992@naver.com

# s3
before_deploy:
  - mkdir -p before-deploy  # zip에 포함시킬 파일들을 담을 디렉토리 생성, travis ci는 디렉토리 단위로 배포 가능하여 디렉토리 생성 필요
  - cp script/*.sh before-deploy/ # before-deploy에는 zip파일에 포함시킬 파일들을 저장
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../** mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springbootAws.zip # deploy로 zip파일 이동

deploy:
  - provider : s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-buildd # S3 버킷명
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접긍을 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-buildd
    key: springbootAws.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true